version: "3.9"

services:
  db:
    image: postgres:14.18-bookworm
    container_name: video_streaming_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: shivam2003
      POSTGRES_DB: fastapi_app
    ports:
      - "5432:5432"
    volumes:
      - video_streaming_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  video_streaming_db_data: